version: "3.8"

services:
  devices-db:
    image: postgres:16
    container_name: devices-db
    environment:
      POSTGRES_DB: devices
      POSTGRES_USER: devices_adm
      POSTGRES_PASSWORD: devices_pwd
    ports:
      - "5432:5432"
    volumes:
      - devices_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devices_adm -d devices"]
      interval: 5s
      timeout: 5s
      retries: 10

  devices-api:
    build:
      context: ./mainApp
      dockerfile: Dockerfile
    image: bologna/devices:0.0.1
    container_name: devices-api
    depends_on:
      devices-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://devices-db:5432/devices
      SPRING_DATASOURCE_USERNAME: devices_adm
      SPRING_DATASOURCE_PASSWORD: devices_pwd
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
volumes:
  devices_db_data:
